/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component;

/**
 *
 * @author ACER
 */
public class CarritoCompra extends javax.swing.JPanel {

    /**
     * Creates new form CarritoCompra
     */
    public CarritoCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarCa = new javax.swing.JButton();
        btnCarritoC = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 2));

        btnAgregarCa.setText("Agregar al Carrito");
        btnAgregarCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCaActionPerformed(evt);
            }
        });
        add(btnAgregarCa);

        btnCarritoC.setText("Carrito Compras");
        add(btnCarritoC);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCaActionPerformed
        
        
    }//GEN-LAST:event_btnAgregarCaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCa;
    private javax.swing.JButton btnCarritoC;
    // End of variables declaration//GEN-END:variables
}
