/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.unicauca.clientclientehttpclient.presentation;

import com.unicauca.clientclientehttpclient.access.ClientRestRepository;
import com.unicauca.clientclientehttpclient.domain.services.ClientService;
import com.unicauca.clientclientehttpclient.domain.entities.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class GUIClient extends javax.swing.JFrame {
    
    private Long idClienteActual;
    ClientService service = new ClientService(new ClientRestRepository());

     
    
    /** Creates new form crud */
    public GUIClient(Long id) {
        this.idClienteActual = id;
        initComponents();
        stateInitial();
    }

    public GUIClient() {
        initComponents();
        stateInitial();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConfirmarElim = new javax.swing.JButton();
        btnConfirmarEdit = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(524, 500));

        jPanel2.setPreferredSize(new java.awt.Dimension(250, 300));
        jPanel2.setLayout(new java.awt.GridLayout(7, 0));

        jLabel7.setText("Nombre:");
        jPanel2.add(jLabel7);

        txtfirstName.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel2.add(txtfirstName);

        jLabel5.setText("Apellido:");
        jPanel2.add(jLabel5);
        jPanel2.add(txtlastName);

        jLabel1.setText("Dirección:");
        jPanel2.add(jLabel1);

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel2.add(txtaddress);

        jLabel3.setText("Nombre de usuario:");
        jPanel2.add(jLabel3);
        jPanel2.add(txtUserName);

        jLabel2.setText("Email:");
        jPanel2.add(jLabel2);
        jPanel2.add(txtEmail);

        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword);

        jLabel6.setText("Confirme que desea eliminar la cuenta");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        btnEditar.setText("Editar mi cuenta");
        btnEditar.setPreferredSize(new java.awt.Dimension(120, 30));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);

        btnEliminar.setText("Eliminar mi cuenta");
        btnEliminar.setPreferredSize(new java.awt.Dimension(130, 30));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);

        btnConfirmarElim.setText("Confirmar");
        btnConfirmarElim.setPreferredSize(new java.awt.Dimension(84, 30));
        btnConfirmarElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarElimActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmarElim);

        btnConfirmarEdit.setText("Confirmar");
        btnConfirmarEdit.setPreferredSize(new java.awt.Dimension(84, 30));
        btnConfirmarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmarEdit);

        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(76, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        stateEditar();
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
            stateEliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConfirmarElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarElimActionPerformed
        service.deleteById(idClienteActual);           
    }//GEN-LAST:event_btnConfirmarElimActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        stateInitial();
        cleanControls();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEditActionPerformed
        Client client = new Client();
            if (txtfirstName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar su nombre", "Error",JOptionPane.ERROR_MESSAGE);         
                txtfirstName.requestFocus();
                return;
            }
            
            if (txtlastName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar su apellido", "Error",JOptionPane.ERROR_MESSAGE);         
                txtlastName.requestFocus();
                return;
            }
            
            if (txtaddress.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar una dirección", "Error",JOptionPane.ERROR_MESSAGE);         
                txtaddress.requestFocus();
                return;
            }
            
            if (txtUserName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un nombre de usuario", "Error",JOptionPane.ERROR_MESSAGE);         
                txtUserName.requestFocus();
                return;
            }
            
            if (txtEmail.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un correo electrónico", "Error",JOptionPane.ERROR_MESSAGE);         
                txtEmail.requestFocus();
                return;
            }
            
            if (txtPassword.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar una contraseña", "Error",JOptionPane.ERROR_MESSAGE);         
                txtPassword.requestFocus();
                return;
            }
            
            String nombre = txtfirstName.getText();
            String apellido = txtlastName.getText();
            String direccion = txtaddress.getText();
            String username = txtUserName.getText();
            String email = txtEmail.getText();
            String contrasenia = txtPassword.getText();

            client.setFirstName(nombre);
            client.setLastName(apellido);
            client.setAddress(direccion);
            //client.setUsername(username);
            //client.setEmail(email);
            //client.setPassword(contrasenia);
            
            service.update(idClienteActual, client);
    }//GEN-LAST:event_btnConfirmarEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIClient().setVisible(true);
            }
        });
    }

    
    private void cleanControls() {
        txtfirstName.setText("");
        txtlastName.setText("");
        txtaddress.setText("");
        txtUserName.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
    }
     private void stateInitial() {
        btnEliminar.setVisible(true);
        btnEditar.setVisible(true);
        btnCancelar.setVisible(false);
        btnConfirmarEdit.setVisible(false);
        btnConfirmarElim.setVisible(false);
        txtfirstName.setEnabled(false);
        txtlastName.setEnabled(false);
        txtaddress.setEnabled(false);
        txtUserName.setEnabled(false);
        txtEmail.setEnabled(false);
        txtPassword.setEnabled(false);
        jLabel6.setVisible(false);
    }
    
    private void stateEditar() {
        btnEliminar.setVisible(false);
        btnEditar.setVisible(false);
        btnCancelar.setVisible(true);
        btnConfirmarEdit.setVisible(true);
        btnConfirmarElim.setVisible(false);
        txtfirstName.setEnabled(true);
        txtlastName.setEnabled(true);
        txtaddress.setEnabled(true);
        txtUserName.setEnabled(true);
        txtEmail.setEnabled(true);
        txtPassword.setEnabled(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel7.setVisible(true);
        txtfirstName.setVisible(true);
        txtlastName.setVisible(true);
        txtaddress.setVisible(true);
        txtUserName.setVisible(true);
        txtEmail.setVisible(true);
        txtPassword.setVisible(true);
        jLabel6.setVisible(false);
    }
    
     private void stateEliminar() {
        btnEliminar.setVisible(false);
        btnEditar.setVisible(false); 
        btnCancelar.setVisible(true);
        btnConfirmarEdit.setVisible(false);
        btnConfirmarElim.setVisible(true);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
        txtfirstName.setVisible(false);
        txtlastName.setVisible(false);
        txtaddress.setVisible(false);
        txtUserName.setVisible(false);
        txtEmail.setVisible(false);
        txtPassword.setVisible(false);
        jLabel6.setVisible(true);
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarEdit;
    private javax.swing.JButton btnConfirmarElim;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtfirstName;
    private javax.swing.JTextField txtlastName;
    // End of variables declaration//GEN-END:variables

}
