/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.clientclientehttpclient.presentation;

import com.unicauca.clientclientehttpclient.access.ClientRestRepository;
import com.unicauca.clientclientehttpclient.domain.entities.Client;
import com.unicauca.clientclientehttpclient.domain.entities.Role;
import com.unicauca.clientclientehttpclient.domain.entities.User;
import com.unicauca.clientclientehttpclient.domain.services.ClientService;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class GUILogin extends javax.swing.JFrame {
    
    ClientService service = new ClientService(new ClientRestRepository());

       /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
        llenarRoles();
    }

    
    public Long verificarInicioSesion(String email, String password){
        String seleccionado = (String) cbxRoles.getSelectedItem();
        System.out.println("Rol escogido: "+seleccionado);
        List<User> users = service.findByRoleName(seleccionado);
        for(User user : users){
            System.out.println("User de rol: "+user.getUserName());
        }
        
        Long idActual;
        for (User user : users) {
            if (user.getUserEmail().equals(email) && user.getUserPassword().equals(password)) {
                idActual = user.getUserId();
                System.out.println("INICIO DE SESION CORRECTO");
                return idActual;
            }
        }
        return -1L;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        cbxRoles = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 250));

        btnEntrar.setText("Acceder");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar);

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras);

        jPanel1.add(cbxRoles);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Email:");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel2.add(jLabel1);
        jPanel2.add(txtEmail);

        jLabel2.setText("Contraseña:");
        jPanel2.add(jLabel2);
        jPanel2.add(txtPassword);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
        if (txtEmail.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el email", "Error", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
            return;
        }
        if (txtPassword.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            txtPassword.requestFocus();
            return;
        }
        
        String email = txtEmail.getText();
        String contrasenia = txtPassword.getText();
        
        Long idActual = verificarInicioSesion(email,contrasenia);
        if(idActual != -1){
            JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            GUIClient instance = new GUIClient(idActual);
            instance.setVisible(true);
           
        }else{
            JOptionPane.showMessageDialog(null, "Inicio de sesión fallido. Verifica tu email, contraseña y rol.", "Error",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        setVisible(false);
        dispose();                  
        GUIPcpal instance = new GUIPcpal();
        instance.setVisible(true);
        
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JComboBox<String> cbxRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    public void llenarRoles(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        List<Role> roles = service.findAllRoles();
        for(Role role : roles){
            model.addElement(role.getRoleName());
        }
        cbxRoles.setModel(model);
    }
}
