/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.clientclientehttpclient.presentation;

import com.unicauca.clientclientehttpclient.access.ClientRestRepository;
import com.unicauca.clientclientehttpclient.domain.entities.Client;
import com.unicauca.clientclientehttpclient.domain.entities.Role;
import com.unicauca.clientclientehttpclient.domain.entities.User;
import com.unicauca.clientclientehttpclient.domain.services.ClientService;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class GUIRegistro extends javax.swing.JFrame {

        ClientService service = new ClientService(new ClientRestRepository());
    /**
     * Creates new form GUIRegistro
     */
    public GUIRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(6, 0));

        jLabel7.setText("Nombre:");
        jPanel2.add(jLabel7);

        txtfirstName.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel2.add(txtfirstName);

        jLabel5.setText("Apellido:");
        jPanel2.add(jLabel5);
        jPanel2.add(txtlastName);

        jLabel1.setText("Dirección:");
        jPanel2.add(jLabel1);

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel2.add(txtaddress);

        jLabel3.setText("Nombre de usuario:");
        jPanel2.add(jLabel3);
        jPanel2.add(txtUserName);

        jLabel2.setText("Email:");
        jPanel2.add(jLabel2);
        jPanel2.add(txtEmail);

        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        btnConfirmar.setText("Confirmar registro");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
            
            Client client = new Client();
            User user = new User();
            if (txtfirstName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar su nombre", "Error",JOptionPane.ERROR_MESSAGE);         
                txtfirstName.requestFocus();
                return;
            }
            
            if (txtlastName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar su apellido", "Error",JOptionPane.ERROR_MESSAGE);         
                txtlastName.requestFocus();
                return;
            }
            
            if (txtaddress.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar una dirección", "Error",JOptionPane.ERROR_MESSAGE);         
                txtaddress.requestFocus();
                return;
            }
            
            if (txtUserName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un nombre de usuario", "Error",JOptionPane.ERROR_MESSAGE);         
                txtUserName.requestFocus();
                return;
            }
            
            if (txtEmail.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un correo electrónico", "Error",JOptionPane.ERROR_MESSAGE);         
                txtEmail.requestFocus();
                return;
            }
            
            if (txtPassword.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar una contraseña", "Error",JOptionPane.ERROR_MESSAGE);         
                txtPassword.requestFocus();
                return;
            }
            
            String nombre = txtfirstName.getText();
            String apellido = txtlastName.getText();
            String direccion = txtaddress.getText();
            String username = txtUserName.getText();
            String email = txtEmail.getText();
            String contrasenia = txtPassword.getText();
            client.setFirstName(nombre);
            client.setLastName(apellido);
            client.setAddress(direccion);
            user.setUserName(username);
            user.setUserEmail(email);
            user.setUserPassword(contrasenia);
            
            List<Role> role = buscarRolVisitante();
            
            user.setUserRoles(role);
            
            service.create(client, user);  
            
            RegresarPcpal();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       
          RegresarPcpal();
          
            
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void RegresarPcpal(){
        setVisible(false);
        dispose();                  
        GUIPcpal instance = new GUIPcpal();
        instance.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtfirstName;
    private javax.swing.JTextField txtlastName;
    // End of variables declaration//GEN-END:variables

    private List<Role> buscarRolVisitante(){
        List<Role> rolesRet = new ArrayList<>();
        List<Role> roles = service.findAllRoles();
        for(Role role : roles){
            if(role.getRoleName().equals("Visitante_Registrado")){
                System.out.println("Entra a visitante reg");
                rolesRet.add(role);
            }
        }
        return rolesRet;
    }

}
