/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.com.hyunseda.market.presentation;

//import com.raven.form.FormHome;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author ACER
 */
public class GUIProduct2 extends javax.swing.JFrame {

    /**
     * Creates new form GUIProduct2
     */
   // private FormHome home;

    public GUIProduct2() {
        initComponents();
       // setBackground(new Color(0, 0, 0, 0));
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNorte = new javax.swing.JPanel();
        PanerSur = new javax.swing.JPanel();
        PanelEste = new javax.swing.JPanel();
        PnlCategory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelNorte.setBackground(new java.awt.Color(255, 255, 255));
        PanelNorte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelNorte.setForeground(new java.awt.Color(255, 255, 255));
        PanelNorte.setOpaque(false);
        getContentPane().add(PanelNorte, java.awt.BorderLayout.PAGE_START);

        PanerSur.setBackground(new java.awt.Color(224, 224, 224));
        getContentPane().add(PanerSur, java.awt.BorderLayout.PAGE_END);

        PanelEste.setBackground(new java.awt.Color(255, 255, 255));

        PnlCategory.setBackground(new java.awt.Color(255, 255, 255));
        PnlCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PnlCategory.setMaximumSize(new java.awt.Dimension(32767, 50000));
        PnlCategory.setLayout(new java.awt.GridLayout(20, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setText("Categorias                       ");
        PnlCategory.add(jLabel2);

        PanelEste.add(PnlCategory);

        getContentPane().add(PanelEste, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   private void init() {
       // home = new FormHome();
       // winButton.initEvent(this, background1);
       // mainPanel.setLayout(new BorderLayout());
       // mainPanel.add(home);
        //testData();*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEste;
    private javax.swing.JPanel PanelNorte;
    private javax.swing.JPanel PanerSur;
    private javax.swing.JPanel PnlCategory;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
