/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.access.ItemRestRepository;
import co.com.hyunseda.market.service.OrderService;
import co.com.hyunseda.market.access.OrderRestRepository;
import co.com.hyunseda.market.service.ItemService;
import co.unicauca.microkernel.common.entities.Item;
import co.unicauca.microkernel.common.entities.Order;
import com.raven.component.PanelAction;
import com.raven.swing.TableActionCellEditor;
import com.raven.swing.TableActionCellRender;
import com.raven.swing.TableActionEvent;
import com.sun.tools.javac.jvm.Items;
import java.sql.Array;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X1605
 */
public class OrdersInfo extends javax.swing.JFrame {

    
     OrderService orderService = new OrderService(new OrderRestRepository());
     
    /**
    /**
     * Creates new form OrdersInfo
     */
    public OrdersInfo() {
        initComponents();
        initializeTable();
        fillTable(orderService.findAll());
        TableActionEvent event = new TableActionEvent(){
            @Override
            public void onSearch() {
                System.out.println("Entra a editar");
               }
        
        };
        tbOrder.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());
        tbOrder.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditor(event));
        tbOrder.setRowSelectionAllowed(true);
        tbOrder.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Agregar un listener para obtener el ID de la orden seleccionada
        tbOrder.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int filaSeleccionada = tbOrder.getSelectedRow();
                if (filaSeleccionada != -1) {
                    Long idOrden = (Long) tbOrder.getValueAt(filaSeleccionada, 0); // Obtener valor de la primera columna (ID)
                    //String[] items = orderService.findAll(); // Consultar el servicio para obtener los items
                    //mostrarItems(items); // Mostrar los items en otro frame
                    System.out.println("Id seleccionado"+idOrden);
                    tbOrder.clearSelection();
                     ItemsInfo info = new ItemsInfo(idOrden);
                     info.setVisible(true);
                }
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrder = new javax.swing.JTable();
        btnConsultarItems = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbOrder);

        btnConsultarItems.setText("Consultar Items");
        btnConsultarItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarItemsActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultarItems)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarItems)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Ordenes Realizadas");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarItemsActionPerformed
        // TODO add your handling code here:
         // Permitir la selección de filas
        dispose();

// O bien, ocultar el JFrame sin liberar los recursos
        setVisible(false);
       

    }//GEN-LAST:event_btnConsultarItemsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();

// O bien, ocultar el JFrame sin liberar los recursos
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
private void fillTable(List<Order> listOrders) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tbOrder.getModel();
        
        Object rowData[] = new Object[4];//No columnas
        for (int i = 0; i <listOrders.size(); i++) {
            rowData[0] = listOrders.get(i).getId();
            rowData[1] = listOrders.get(i).getState();
            rowData[2] = listOrders.get(i).getDate();
            rowData[3] = listOrders.get(i).getState();
            
            model.addRow(rowData);
        }
    }
    private void initializeTable() {
        tbOrder.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID Orden", "Estado", "Fecha Orden", "Items"
                }
        ));
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarItems;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbOrder;
    // End of variables declaration//GEN-END:variables
}
