
package com.unicauca.clientuserhttpclient.presentation;

import com.unicauca.clientuserhttpclient.domain.services.UserService;
import java.util.List;
import com.unicauca.clientuserhttpclient.domain.entities.User;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author libardo
 */
public class GUIProductsList extends javax.swing.JDialog {
    private UserService service;
    /**
     * Creates new form GUIProductsList
     */
    public GUIProductsList(java.awt.Frame parent, boolean modal, UserService service) {
        super(parent, modal);
        this.service = service;
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar productos");

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void InitializeTable() {
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Nombre", "Precio"
                }
        ));
    }

    private void loadData() {
        InitializeTable();
        List<User> result = service.findDifferentRoleVisitor();
        this.InitializeTable();
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();

        Object rowData[] = new Object[8];//No columnas
        for (int i = 0; i < result.size(); i++) {
            /*rowData[0] = result.get(i).getId();
            rowData[1] = result.get(i).getName();
            rowData[2] = "" + result.get(i).getPrice();*/

            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
}
