/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.clientuserhttpclient.presentation;

import com.unicauca.clientuserhttpclient.access.UserRestRepository;
import com.unicauca.clientuserhttpclient.domain.entities.User;
import com.unicauca.clientuserhttpclient.domain.services.UserService;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Felipe Castro
 */
public class GUIUser extends javax.swing.JFrame {

    UserService userService = new UserService(new UserRestRepository());
    
    GUIUserOption guiUserOption;
    
    
    /**
     * Creates new form GUIUser
     */
    public GUIUser() {
        initComponents();
        cargarTablaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 350));

        jPanel1.setMinimumSize(new java.awt.Dimension(314, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 35));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);

        btnCerrar.setText("Cerrar");
        jPanel1.add(btnCerrar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblUsers);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow != -1) { // Asegúrate de que se haya seleccionado una fila
            // Supongamos que deseas obtener el valor de la primera columna
            Long userId = (Long) tblUsers.getValueAt(selectedRow, 0);
            //Long userId = Long.parseLong(value);
            
            guiUserOption = new GUIUserOption(1, userId);
            guiUserOption.setVisible(true);
            this.setVisible(false);
            dispose();
        }else{
            Messages.showMessageDialog("Por favor seleccione cual usuario desea editar", "Atención");
            return;
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        guiUserOption = new GUIUserOption(0);
        guiUserOption.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow != -1) { // Asegúrate de que se haya seleccionado una fila
            // Supongamos que deseas obtener el valor de la primera columna
            Long userId = (Long) tblUsers.getValueAt(selectedRow, 0);
            //Long userId = Long.parseLong(value);
            
            userService.delete(userId);
            Messages.showMessageDialog("El usuario seleccionado se ha borrado correctamente", "Confirmación");
            cargarTablaUsuarios();
        }else{
            Messages.showMessageDialog("Por favor seleccione cual usuario desea eliminar", "Atención");
            return;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables

    //Funciones necesarias
    private void cargarTablaUsuarios(){
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Nombre de usuario", "Email", "Cotraseña", "Rol(es)"
                }
        ));
        List<User> users = userService.findDifferentRoleVisitor();
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();

        Object rowData[] = new Object[8];//No columnas
        for (int i = 0; i < users.size(); i++) {
            rowData[0] = users.get(i).getUserId();
            rowData[1] = users.get(i).getUserName();
            rowData[2] = users.get(i).getUserEmail();
            rowData[3] = users.get(i).getUserPassword();
            
            rowData[4] = users.get(i).getUserRolesString();
            
            model.addRow(rowData);
        }
    }
    
    
}
